### PR TITLE
Adding the ability to have different views per platform.

### PR DESCRIPTION
**Pull request by dvh91**
It's a feature request I decided to implement myself and submit a PR.
As I see it, the difference of the platform is crucial to the views.

### CODE REVIEW

**Comment by NathanWalker** [comment]
@dvh91 cool! Thank you for this effort.
Maybe we could make this configurable so as not to force users to make platform specific views?
This may be desired for some projects and not for others. 
Static configuration to opt into this?

**Comment by dvh91** [comment]
@NathanWalker  - I made it configurable in component level as a metadata

**Comment by NathanWalker** [comment]
👍 I'll release a new version after awhile with this. Thanks!

**Comment by NathanWalker** [comment]
Published now with `1.9.0` 👍

**Pull request merged**
